from vending_machine.config.common import *

"""
Django config for doc_manager project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/config/

For the full list of config and their values, see
https://docs.djangoproject.com/en/2.1/ref/config/
"""

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "2f56d$=^kp_ql#^=e9pgx+fcktwf=v3aam278q#kisaluz$=$k"


DEBUG = True

# INSTALLED_APPS += ["silk"]
# MIDDLEWARE += ["silk.middleware.SilkyMiddleware"]

# # Django-silk global variables
# SILKY_PYTHON_PROFILER = True
# SILKY_PYTHON_PROFILER_BINARY = True


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "%(message)s",
        },
        "verbose": {
            "format": "[VENDING_MACHINE] %(levelname)s  %(asctime)s  %(module)s %(process)d  %(thread)d  %(message)s"
        },
    },
    "filters": {

    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "filters": [],
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "loggers": {
        "django": {"handlers": ["console"], "propagate": False, "level": "DEBUG"},
        "": {"handlers": ["console"], "propagate": False, "level": "INFO"},
    },
}
