"""
Django config for doc_manager project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/config/

For the full list of config and their values, see
https://docs.djangoproject.com/en/2.1/ref/config/
"""
import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development config - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
SECRET_KEY = "6)wpti9$mtao03tr^ruf7wu(qdrtl30vl+)1m)elscyxb3v$co"
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.auth",
    "django.contrib.staticfiles",
    "vending_machine.apps.VendingMachineConfig",
    "rest_framework",
    "rest_framework.authtoken",
    "django_extensions",
    "corsheaders",
]
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",  # this is default
)


REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "vending_machine.views.exceptions.custom_exception_handler",
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "shipmnts_utils.auth.token_auth.ExpiringTokenAuthentication",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "ORDERING_PARAM": "ordering",
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "shipmnts_utils.middleware.thread_local_middleware.ThreadLocalMiddleware",
]

CORS_ORIGIN_WHITELIST = (
    "localhost:3000",
)


DB_SEARCH_ENABLED = False

ROOT_URLCONF = "vending_machine.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]
WSGI_APPLICATION = "vending_machine.wsgi.application"
TOKEN_EXPIRED_AFTER_SECONDS = 86400

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

db_name = "vending_machine"
db_user = os.getenv("POSTGRES_USER", "")
db_password = os.getenv("POSTGRES_PASSWORD", "")
host = os.getenv("POSTGRES_HOST", "localhost")
port = os.getenv("POSTGRES_PORT", "5432")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": db_name,
        "USER": db_user,
        "PASSWORD": db_password,
        "HOST": host,
        "PORT": port,
    }
}
AUTH_USER_MODEL = "vending_machine.User"


STATIC_URL = "/static/"
